server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/robot_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  #redis
  #rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: 127.0.0.1
      port: 6379

#mybatis‑plus配置
mybatis‑plus:
  mapper‑locations: classpath:mapper/*.xml
  type‑aliases‑package: com.robot.demo.pojo.po
  configuration:
    map‑underscore‑to‑camel‑case: true
    log‑impl: org.apache.ibatis.logging.stdout.StdOutImpl
